version: '3'
services:
  backend:
    build: ./backend
    container_name: extreme-weather-backend
    ports:
      - "5004:5004"
    volumes:
      - ./backend:/backend
    restart: always
    networks:
      - nginx-proxy

  frontend:
    build: ./frontend
    container_name: extreme-weather-frontend
    ports:
      - "5005:5005"
    volumes:
      - ./frontend:/frontend
    environment:
      VIRTUAL_HOST: extremeweather.ga
      PORT: 5005
    depends_on:
      - backend
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true

