version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5004:5004"
    volumes:
      - ./backend:/backend
    networks:
      - outside

  frontend:
    build: ./frontend
    ports:
      - "5005:5005"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - outside

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - outside

networks:
  outside:
    external:
      name: ExternalNetwork
